"""
Dictionaries of land cover classes
"""

MODIS_LC = {
    1: {'class': 'evg_conif',
        'pct_cov': 0},
    2: {'class': 'evg_broad',
        'pct_cov': 0},
    3: {'class': 'dcd_needle',
        'pct_cov': 0},
    4: {'class': 'dcd_broad',
        'pct_cov': 0},
    5: {'class': 'mix_forest',
        'pct_cov': 0},
    6: {'class': 'cls_shrub',
        'pct_cov': 0},
    7: {'class': 'open_shrub',
        'pct_cov': 0},
    8: {'class': 'woody_savanna',
        'pct_cov': 0},
    9: {'class': 'savanna',
        'pct_cov': 0},
    10: {'class': 'grassland',
         'pct_cov': 0},
    11: {'class': 'perm_wetland',
         'pct_cov': 0},
    12: {'class': 'cropland',
         'pct_cov': 0},
    13: {'class': 'urban',
         'pct_cov': 0},
    14: {'class': 'crop_nat_veg',
         'pct_cov': 0},
    15: {'class': 'perm_snow',
         'pct_cov': 0},
    16: {'class': 'barren',
         'pct_cov': 0},
    17: {'class': 'water_bds',
         'pct_cov': 0}
}

FIRE_LC = {
    0: {'class': 'crop_rain',
        'pct_cov': 0},
    20: {'class': 'crop_irr',
         'pct_cov': 0},
    30: {'class': 'crop_veg',
         'pct_cov': 0},
    40: {'class': 'veg_crop',
         'pct_cov': 0},
    50: {'class': 'broad_ever',
         'pct_cov': 0},
    60: {'class': 'broad_decid',
         'pct_cov': 0},
    70: {'class': 'needle_ever',
         'pct_cov': 0},
    80: {'class': 'needle_decid',
         'pct_cov': 0},
    90: {'class': 'tree_mixed',
         'pct_cov': 0},
    100: {'class': 'tree_shrub_herb',
          'pct_cov': 0},
    110: {'class': 'herb_tree_shrub',
          'pct_cov': 0},
    120: {'class': 'shrubland',
          'pct_cov': 0},
    130: {'class': 'grassland',
          'pct_cov': 0},
    140: {'class': 'lichen_moss',
          'pct_cov': 0},
    150: {'class': 'sparse_veg',
          'pct_cov': 0},
    170: {'class': 'tree_flooded',
          'pct_cov': 0},
    180: {'class': 'shrub_herb_flood',
          'pct_cov': 0},
    160: {'class': 'unburnt',
          'pct_cov': 0}
}